### ISSUE TITLE
Invalid Image URL with error code 400 in add_python_faces.py

### ISSUE THREAD

**Issue by sumit-raj-au5** [chetanyachopra/FaceRecognition-Attendance-Marking#1]
E:\Face Attendance>python add_person_faces.py user05
User.05.1.jpg
imageurl = E:/Face%20Attendance/dataset/user05/User.05.1.jpg
Traceback (most recent call last):
  File "add_person_faces.py", line 42, in <module>
    res = CF.face.detect(imgurl)
  File "C:\ProgramData\Anaconda3\lib\site-packages\cognitive_face\face.py", line 41, in detect
    'POST', url, headers=headers, params=params, json=json, data=data)
  File "C:\ProgramData\Anaconda3\lib\site-packages\cognitive_face\util.py", line 105, in request
    error_msg.get('message'))
cognitive_face.util.CognitiveFaceException: Error when calling Cognitive Face API:
        status_code: 400
        code: InvalidURL
        message: Invalid image URL.

**Comment by Rupesh-Ghimire** [comment]
how to get the face api key from microsoft? or i can use the same api as used in this project?

**Comment by chetanyachopra22** [comment]
Hey, @raj-sumit please convert path of image to url scheme as done in `urllib.request.pathname2url(os.path.join(imageFolder, filename))` as `CF.detects()` only reads url scheme
* Please refer to the microsoft's cognitive services documentation it'll help you

**Comment by chetanyachopra22** [comment]
@Rupesh-Ghimire  nah man, this key is broken, I think this is depreciated now .. I wouldn't  placed key linked to my account ..... but i dont remember really. I worked on this few years back.. 
* To generate your own key refer to the microsoft's cognitive services doc 
Cheers

**Comment by Rupesh-Ghimire** [comment]
I generate the key for seven days free trial but still not working?

**Comment by chetanyachopra22** [comment]
@Rupesh-Ghimire please describe error log here and steps to reproduce it !!

**Comment by Rupesh-Ghimire** [comment]
rupesh@rupesh-Aspire-E5-575:~/PycharmProjects/Autoattendance-Cognitive-master$ python create_person.py user38
Traceback (most recent call last):
  File "create_person.py", line 11, in <module>
    res = CF.person.create(personGroupId, str(sys.argv[1]))
  File "/home/rupesh/anaconda3/lib/python3.6/site-packages/cognitive_face/person.py", line 71, in create
    return util.request('POST', url, json=json)
  File "/home/rupesh/anaconda3/lib/python3.6/site-packages/cognitive_face/util.py", line 105, in request
    error_msg.get('message'))
cognitive_face.util.CognitiveFaceException: Error when calling Cognitive Face API:
	status_code: 404
	code: PersonGroupNotFound
	message: Person group is not found.
Parameter name: personGroupId

**Comment by Rupesh-Ghimire** [comment]
i used subscription key from microsoft face api... still getting the error like below:
rupesh@rupesh-Aspire-E5-575:~/PycharmProjects/Autoattendance-Cognitive-master$ python train.py
Traceback (most recent call last):
  File "train.py", line 9, in <module>
    res = CF.person_group.train(personGroupId)
  File "/home/rupesh/anaconda3/lib/python3.6/site-packages/cognitive_face/person_group.py", line 119, in train
    return util.request('POST', url)
  File "/home/rupesh/anaconda3/lib/python3.6/site-packages/cognitive_face/util.py", line 105, in request
    error_msg.get('message'))
cognitive_face.util.CognitiveFaceException: Error when calling Cognitive Face API:
	status_code: 401
	code: Unspecified
	message: Access denied due to invalid subscription key. Make sure you are subscribed to an API you are trying to call and provide the right key.

**Comment by chetanyachopra22** [comment]
@Rupesh-Ghimire make sure region you used while generating api key is same as the region in url you are hitting or make the subsequent changes in the url see the docs for it
